---
- name: install docker packages
  package:
    name: "{{ package }}"
    state: present
  loop: "{{ docker_registry_setup_packages }}"
  loop_control:
    loop_var: package
  notify: "restart docker"

- name: configure firewalld for docker
  firewalld:
    port:  "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ docker_registry_setup_ports }}"
  notify:
    - "restart firewalld"
  when: docker_registry_setup_firewall == 'firewalld'

- block:
    - name: check iptables for open local port
      command: iptables --list INPUT --numeric
      register: undercloud_iptables_input_chain

    - set_fact:
        undercloud_iptables_intput_chain_local_port_line: "{{ line }}"
      when: line is search('^ACCEPT.*tcp.*dport.*' + docker_registry_setup_local_port|string)
      loop: "{{ undercloud_iptables_input_chain.stdout_lines }}"
      loop_control:
        loop_var: line

    - name: configure iptables for docker
      iptables:
        action: insert
        rule_num: 1
        chain: INPUT
        protocol: "{{ port.split('/').1 }}"
        destination_port: "{{ port.split('/').0 }}"
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: "Accept incoming docker registry requests - added by Ansible"
      loop: "{{ docker_registry_setup_ports }}"
      loop_control:
        loop_var: port
      notify:
        - "restart iptables"
      when: undercloud_iptables_intput_chain_local_port_line is not defined
  when: docker_registry_setup_firewall == 'iptables'

# I could not find a good way to do a regex search for begining of line (^). the 'search()' test was not working properly and I wanted to be sure I was not catching a commented out line as a false positive.
- name: check if insecure registry option already added to /etc/sysconfig/docker
  command: grep "^INSECURE_REGISTRY=.*" /etc/sysconfig/docker
  register: docker_registry_option_check
  ignore_errors: true

- set_fact:
    docker_registry_option_in_config: True
  when: docker_registry_option_check.rc == 0

- name: add registry option config to '/etc/sysconfig/docker' if needed
  lineinfile:
    dest: '/etc/sysconfig/docker'
    line: 'INSECURE_REGISTRY="--insecure-registry {{ docker_registry_setup_local_hostname }}:{{ docker_registry_setup_local_port }} --insecure-registry {{ docker_registry_setup_upstream_hostname }}:{{ docker_registry_setup_upstream_port }}"'
    state: present
  notify: "restart docker"
  when: docker_registry_option_in_config | default(False) | bool == False

- name: retrieve /etc/sysconfig/docker
  slurp:
    src: /etc/sysconfig/docker
  register: docker_config

- name: check if registry urls already added to /etc/sysconfig/docker
  set_fact:
    docker_urls_in_config: True
  when: 
    - (docker_config.content | b64decode ) is search(docker_registry_setup_local_hostname)
    - (docker_config.content | b64decode ) is search(docker_registry_setup_upstream_hostname)

- name: add config to '/etc/sysconfig/docker' if needed
  lineinfile:
    dest: '/etc/sysconfig/docker'
    line: 'INSECURE_REGISTRY="--insecure-registry {{ docker_registry_setup_local_hostname }}:{{ docker_registry_setup_local_port }} --insecure-registry {{ docker_registry_setup_upstream_hostname }}:{{ docker_registry_setup_upstream_port }}"'
    regexp: '^INSECURE_REGISTRY=.*$'
    state: present
  notify: "restart docker"
  when:
    - docker_urls_in_config | default(False) | bool == False
    - docker_registry_option_in_config | default(False) | bool == True

- name: set fact if docker was already configured
  set_fact:
    docker_registry_setup_configured: True
  when: 
    - docker_registry_option_in_config | default(False) | bool == True
    - docker_urls_in_config | default(False) | bool == True

# Restart services right away
- meta: flush_handlers
...
