---
- name: install container image utiilty
  package:
    name: "{{ docker_registry_setup_container_image_utility }}"
    state: present

- name: retrieve container image metadata from upstream registry
  command: "skopeo inspect docker://{{ docker_registry_setup_upstream_hostname }}:{{ docker_registry_setup_upstream_port }}/{{ docker_registry_setup_image_namespace }}/{{ docker_registry_setup_image_prefix }}{{ image.imagename }}"
  loop: "{{ docker_registry_setup_container_images }}"
  loop_control:
    loop_var: image
  register: container_image_metadata

- name: show discovered tags for image
  debug:
    msg: "Discovered tags for image='{{ metadata.image.imagename }}' tags='{{ (metadata.stdout | from_json).RepoTags }}'"
    verbosity: 1
  loop: "{{ container_image_metadata.results }}"
  loop_control:
    loop_var: metadata
    label: "{{ (metadata.stdout | from_json).RepoTags }}"

- include_tasks: sync_by_tag.yml
  loop: "{{ container_image_metadata.results }}"
  loop_control:
    loop_var: metadata
    label: "{{ (metadata.stdout | from_json).RepoTags }}"
...
