---
- hosts: registry
  tasks:
    - import_role:
        name: docker-registry-setup
      vars:
        docker_registry_setup_undercloud_check: False
        docker_registry_setup_on_undercloud: False
        docker_registry_setup_image_rhosp_version: rhosp12


- hosts: undercloud
  tasks:
    - import_role:
        name: docker-registry-setup
      vars:
        docker_registry_setup_undercloud_check: False
        docker_registry_setup_on_undercloud: True
        docker_registry_setup_upstream_hostname: 'registry.example.com'
        docker_registry_setup_upstream_port: '8787'
        docker_registry_setup_image_rhosp_version: rhosp12
...
