---
docker_registry_setup_upstream_hostname: registry.access.redhat.com
# This should be the same as undercloud, for now just setting static example IP but can be in inventory
docker_registry_setup_local_hostname: "{{ inventory_hostname }}"
#docker_registry_setup_local_hostname: "{{ ansible_all_ipv4_addresses | ipaddr(provisioning_cidr) | first() }}"
docker_registry_setup_upstream_port: ''
docker_registry_setup_local_port: 5000
docker_registry_setup_url_suffix: "/v2/_catalog"
docker_registry_setup_image_prefix: "openstack-"
docker_registry_setup_image_rhosp_version: rhosp13
docker_registry_setup_image_tag: latest
docker_registry_setup_upstream_images_file: "upstream-container-images.yaml"
docker_registry_setup_overcloud_images_file: "overcloud-images.yaml"
docker_registry_setup_sync: True
docker_registry_setup_force: False
docker_registry_setup_packages:
  - docker
  - docker-distribution
  - docker-python
  - python-docker-py
docker_registry_setup_services:
  - docker
  - docker-distribution
docker_registry_setup_ports:
  - 5000/tcp

# Container images to populate in registry
# This list was taken from the overcloud-images.yaml that `openstack overcloud container image prepare` command outputs. As that file contains several variables used in the deployment, several of the container images are the same, thus causing duplicates. This list has been cleaned up of all dupes.
docker_registry_setup_images:
  - aodh-api
  - aodh-evaluator
  - aodh-listener
  - aodh-notifier
  - ceilometer-compute
  - ceilometer-central
  - ceilometer-notification
  - cinder-api
  - cinder-scheduler
  - cinder-volume
  - mariadb
  - cron
  - glance-api
  - gnocchi-api
  - gnocchi-metricd
  - gnocchi-statsd
  - haproxy
  - heat-api-cfn
  - heat-api
  - heat-engine
  - horizon
  - iscsid
  - keystone
  - memcached
  - mariadb
  - neutron-server
  - neutron-dhcp-agent
  - neutron-l3-agent
  - neutron-metadata-agent
  - nova-api
  - nova-compute
  - nova-conductor
  - nova-api
  - nova-consoleauth
  - nova-compute
  - nova-libvirt
  - nova-api
  - nova-placement-api
  - nova-scheduler
  - nova-novncproxy
  - neutron-openvswitch-agent
  - panko-api
  - rabbitmq
  - redis
  - swift-account
  - swift-proxy-server
  - swift-container
  - swift-object
  - swift-proxy-server
...
