---
# Packages
- name: check if this system has {{ package }}
  command: rpm -q {{ package }}
  register: package_status
  no_log: "True"
  ignore_errors: yes
  loop: "{{ docker_registry_setup_undercloud_profile.packages }}"
  loop_control:
    loop_var: package

- name: set fact if packages match
  set_fact:
    docker_registry_setup_undercloud_packages: True 
  when: not package.failed | default(None)
  loop: "{{ package_status.results }}"
  loop_control:
    loop_var: package
    
# Services
- name: check if this system has {{ service }}
  command: systemctl status {{ service }}
  no_log: "True"
  register: service_status
  ignore_errors: yes
  loop: "{{ docker_registry_setup_undercloud_profile.services }}"
  loop_control:
    loop_var: service
  
- name: set fact if services match
  set_fact:
    docker_registry_setup_undercloud_services: True 
  when: not service.failed | default(None)
  loop: "{{ service_status.results }}"
  loop_control:
    loop_var: service
    
# Files
- name: check if this system has {{ file }}
  stat:
    path: "{{ file }}"
  register: file_status
  ignore_errors: yes
  loop: "{{ docker_registry_setup_undercloud_profile.files }}"
  loop_control:
    loop_var: file

- name: set fact if files match
  set_fact:
    docker_registry_setup_undercloud_files: True 
  when: file.stat.exists | default(False)
  loop: "{{ file_status.results }}"
  loop_control:
    loop_var: file

# Dirs
- name: check if this system has {{ dir }}
  stat:
    path: "{{ dir }}"
  register: dir_status
  loop: "{{ docker_registry_setup_undercloud_profile.dirs }}"
  loop_control:
    loop_var: dir

- name: set fact if dirs match
  set_fact:
    docker_registry_setup_undercloud_dirs: True 
  when: 
    - dir.stat.exists | default(False)
    - dir.stat.isdir | default(False)
  loop: "{{ dir_status.results }}"
  loop_control:
    loop_var: dir

-  set_fact:
    docker_registry_setup_on_undercloud: False

# Set undercloud option if everything matches
- name: set fact if host profile matches undercloud
  set_fact:
    docker_registry_setup_on_undercloud: True
  when:
    - docker_registry_setup_undercloud_packes | default(False) | bool == True
    - docker_registry_setup_undercloud_services | default(False) | bool == True
    - docker_registry_setup_undercloud_files | default(False) | bool == True
    - docker_registry_setup_undercloud_dirs | default(False) | bool == True

# Set port to default 8787 if undercloud
  set_fact:
    docker_registry_setup_local_port: 8787
  when: docker_registry_setup_on_undercloud | default(False) | bool == True

- debug:
    var: "{{ item }}"
    verbosity: 1
  loop:
    - "{{ docker_registry_setup_undercloud_packes }}"
    - "{{ docker_registry_setup_undercloud_services }}"
    - "{{ docker_registry_setup_undercloud_files }}"
    - "{{ docker_registry_setup_undercloud_dirs }}"
    - "{{ docker_registry_setup_local_port }}"

- pause:
...
