---
- name: download images from upstream registry {{ docker_registry_setup_upstream_hostname }} and upload into local undercloud registry at {{ docker_registry_setup_local_hostname }}
  shell: . /home/stack/stackrc ; openstack overcloud container image upload \
      --verbose \
      --config-file {{ docker_registry_setup_upstream_images_file }}
...
